### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by izziaraffaele** [saxulum/saxulum-doctrine-mongodb-odm-provider#3]
This is the error I'm getting. Looks like composer cannot find doctrine/mongodb-odm 1.*@beta. I'm getting this error trying to require both v2 and v1.1.

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for saxulum/saxulum-doctrine-mongodb-odm-provider 1.0.0 -> satisfiable by saxulum/saxulum-doctrine-mongodb-odm-provider[1.0.0].
    - saxulum/saxulum-doctrine-mongodb-odm-provider 1.0.0 requires doctrine/mongodb-odm 1.*@beta -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by dominikzogg** [comment]
@izziaraffaele do you allow to install beta packages within your project composer.json?

**Comment by izziaraffaele** [comment]
@dominikzogg  this is my composer.json

{
    "name": "izziaraffaele/webcomposer",
    "description": "A suite of PHP components that you can use to compose your application",
    "authors": [
        {
            "name": "Izzia Raffaele",
            "email": "izziaraffaele@gmail.com"
        }
    ],
    "require": {
        "php": ">=5.3",
        "silex/silex": "~1.2",
        "igorw/config-service-provider": "~1.2",
        "saxulum/saxulum-doctrine-mongodb-odm-provider": "1.1.0"
    },
    "require-dev": {
        "phpunit/phpunit": "~4.5"
    },
    "autoload": {
        "psr-0": {
            "WebComposer\\": "./src"
        }
    }
}

**Comment by izziaraffaele** [comment]
Using "minimum-stability":"dev" and "prefer-stable": true it worked. I had to set those parameters also in the composer.json file of the main project that is using my WebComposer package

**Comment by dominikzogg** [comment]
@izziaraffaele "minimum-stability":"beta" within your root composer.json (project) should be enough, or you add the odm itself also within the root composer.json with @beta.

**Comment by aequasi** [comment]
```
✘ aaron@Aarons-MBP  ~/Projects/sctr/tracker.bang.com/project  ± master ●✚  composer require saxulum/saxulum-doctrine-mongodb-odm-provider                                                             ⏎
Using version ~2.0 for saxulum/saxulum-doctrine-mongodb-odm-provider
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for saxulum/saxulum-doctrine-mongodb-odm-provider ~2.0 -> satisfiable by saxulum/saxulum-doctrine-mongodb-odm-provider[2.0.0].
    - saxulum/saxulum-doctrine-mongodb-odm-provider 2.0.0 requires saxulum/saxulum-doctrine-mongodb-provider ~2.0 -> satisfiable by saxulum/saxulum-doctrine-mongodb-provider[2.0.0].
    - Conclusion: remove pimple/pimple v1.1.1
    - saxulum/saxulum-doctrine-mongodb-provider 2.0.0 requires pimple/pimple >=2.1,<4 -> satisfiable by pimple/pimple[v2.1.0, v2.1.1, v3.0.0].
    - Can only install one of: pimple/pimple[v2.1.0, v1.1.1].
    - Can only install one of: pimple/pimple[v2.1.1, v1.1.1].
    - Can only install one of: pimple/pimple[v3.0.0, v1.1.1].
    - Installation request for pimple/pimple == 1.1.1.0 -> satisfiable by pimple/pimple[v1.1.1].


Installation failed, reverting ./composer.json to its original content.
```

```json
{
    "minimum-stability": "beta",
    "prefer-stable":     true,
    "require":           {
        "silex/silex":              "~1.2",
        "aequasi/environment":      "~1.0",
        "symfony/options-resolver": "~2.6",
        "raulfraile/ladybug":       "~1.0"
    }
}

```

**Comment by dominikzogg** [comment]
@aequasi for silex1 (which means pimple 1) you need the provider ~1.1
